project_id = "601312f6-accf-461c-ab0d-cfc12d476bfe"

[functions.send-portal-invite]
verify_jwt = false

[functions.send-content-approval-request]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.get-proposal]
verify_jwt = false

[functions.sign-proposal]
verify_jwt = false
