-- 014_finance_module.sql
-- Documentational migration (schema already applied directly in Supabase).
-- Adds invoicing, invoice_items, and payments tables plus workspace/client
-- billing extensions.
--
-- NOTE: This file mirrors the production schema for repo history; do not
-- re-run against a live database that already has these tables.

-- 1. Clients — billing extension
alter table if exists public.clients
  add column if not exists stripe_customer_id text;

-- 2. Workspaces — finance defaults
alter table if exists public.workspaces
  add column if not exists default_tax_rate numeric(6,3) not null default 0,
  add column if not exists default_payment_terms_days integer not null default 15,
  add column if not exists invoice_notes_default text;

-- 3. Invoices
create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete restrict,
  project_id uuid null references public.projects(id) on delete set null,
  invoice_number text unique,  -- auto-generated by trigger on insert (INV-YYYY-####)
  status text not null default 'draft'
    check (status in ('draft','sent','paid','partial','overdue','void')),
  issue_date date not null default current_date,
  due_date date not null,
  currency text not null default 'usd',
  subtotal numeric(14,2) not null default 0,
  tax_rate numeric(6,3) not null default 0,
  tax_amount numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  amount_paid numeric(14,2) not null default 0,
  is_recurring boolean not null default false,
  recurrence_interval text
    check (recurrence_interval in ('monthly','quarterly','yearly')),
  notes text,
  terms text,
  stripe_customer_id text,
  stripe_invoice_id text,
  stripe_hosted_invoice_url text,
  stripe_invoice_pdf text,
  sent_at timestamptz,
  paid_at timestamptz,
  void_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 4. Invoice items
create table if not exists public.invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  project_id uuid null references public.projects(id) on delete set null,
  description text not null,
  quantity numeric(12,3) not null default 1,
  unit_price numeric(14,2) not null default 0,
  amount numeric(14,2) generated always as (quantity * unit_price) stored,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- 5. Payments
create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  invoice_id uuid null references public.invoices(id) on delete set null,
  client_id uuid not null references public.clients(id) on delete restrict,
  amount numeric(14,2) not null,
  currency text not null default 'usd',
  method text not null check (method in ('stripe','ach','check','cash','wire','other')),
  status text not null default 'succeeded'
    check (status in ('pending','succeeded','failed','refunded')),
  stripe_payment_intent_id text,
  stripe_charge_id text,
  receipt_url text,
  paid_at timestamptz not null default now(),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Triggers/functions (declaration only — see production DB for full bodies):
--   - trg_invoices_assign_number : populates invoice_number on insert
--   - trg_invoice_items_recalc   : recomputes subtotal/tax_amount/total on items change
--   - trg_invoices_recalc_tax    : recomputes tax_amount/total when tax_rate changes
--   - trg_payments_apply         : updates invoices.amount_paid + status when payments change
--   - trg_invoices_notify        : fires notifications (invoice_sent, invoice_paid, ...)

-- RLS: workspace members read/write; portal clients (is_client_user)
-- can SELECT invoices, invoice_items (for their invoices) and payments
-- scoped to their client. Policies applied directly in Supabase.

-- Notification types added to notifications.type check constraint:
--   invoice_sent, invoice_paid, invoice_overdue, invoice_payment_failed
